# Generated by Django 5.1.7 on 2025-05-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_assigned', models.CharField(max_length=100)),
                ('time', models.TextField()),
                ('weekday', models.TextField()),
            ],
        ),
    ]
