# Generated by Django 5.1.7 on 2025-05-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='weekday',
            new_name='day',
        ),
    ]
