# Generated by Django 5.1.7 on 2025-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_weekday_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userlevel',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
