# Generated by Django 5.1.7 on 2025-05-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='es_assigned',
            new_name='days',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='task',
            name='e_assigned',
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='employee_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(),
        ),
    ]
